### ISSUE TITLE
Report generation on build failure.

### ISSUE THREAD

**Issue by myusoof-xinja** [SpacialCircumstances/gradle-cucumber-reporting#13]
Is there a property to generate the report even when the test build has failed.

**Comment by SpacialCircumstances** [comment]
The `test` task is `finalizedBy` the report generation, so it is executed even when a test fails. When an earlier task fails, it is not executed.
What behavior do you expect/would you like to have?

**Comment by myusoof-xinja** [comment]
Sorry for delay in reply. I have few assertion failure and could see that the report is not generated on failures.

**Comment by SpacialCircumstances** [comment]
The reports should be generated, even when tests fail. Do you have anything to reproduce this issue? I have never encountered this before.

**Comment by myusoof-xinja** [comment]
sorry. Looks like the build failed due to assertion and the generateCucumberReport task is not invoked. I am closing the ticket.

**Comment by XavierLevaux** [comment]
Hi @SpacialCircumstances 
First of all, thanks for this great Gradle plugin!

I'm learning BDD and I'm used to Gradle instead of Maven.  So I discovered this plugin and it seems to be the most appropriate one.

But I have the same issue.  I get a build failure when BDD tests steps are pending implementation (throwing PendingException).
Here is my repository: https://gitlab.com/XavierLevaux/cucumber-gradle
If you run tests `./gradlew clean test` or build it `./gradlew clean build`, you get an error:
`

> Task :generateCucumberReports FAILED
Reports file /Volumes/Storage/projects/shoppingcart/output/reports/cucumber-report.json not found
No report files found, aborting...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateCucumberReports'.
> No test files found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
6 actionable tasks: 6 executed
`

**Comment by SpacialCircumstances** [comment]
@XavierLevaux I've taken a look at your project. To me, the issue seems to be that your cucumber task is not invoked when you run `gradle test`. There are two ways to solve this problem:

1. Invoke your cucumber task when invoking tests
By adding `test.dependsOn cucumber` to your build.gradle, your cucumber task will be executed when running `gradle test`. If I do this, reports are generated correctly (the build still fails, because your tests fail with a PendingException).

2. Invoke cucumber task and run report generation after that
By adding `cucumber.finalizedBy generateCucumberReports` report generation will be invoked after running `gradle cucumber`. 
You can use the flag `testTasksFinalizedByReport = false` (see README) to make sure that reports will not be generated after running `gradle test`.

I hope this solves your issue, if not, feel free to ask again (preferably by opening a new issue)!

**Comment by XavierLevaux** [comment]
Thanks @SpacialCircumstances for your time reviewing my problem. 👍 
I've come to a solution.  I build separately the finished features and the WIP ones.
Then when both json reports are done, I merge them and build the report.
Happy to get your thoughts.
